matches = [
    {
        "md5": "003EBEDCC200AC49FF37F651971141C2",
        "matches": [
            {
                "signature": {
                    "accession": "G3DSA:1.10.510.10",
                    "name": None,
                    "description": "Transferase(Phosphotransferase) domain 1",
                    "type": "Homologous_superfamily",
                    "signatureLibraryRelease": {
                        "library": "CATH-Gene3D",
                        "version": "4.3.0",
                    },
                    "entry": None,
                },
                "modelAccession": "5vdkA02",
                "score": 149.9,
                "evalue": 2.2e-43,
                "locations": [
                    {
                        "start": 318,
                        "end": 521,
                        "hmmStart": 3,
                        "hmmEnd": 200,
                        "hmmLength": 205,
                        "evalue": 3.5e-43,
                        "score": 149.3,
                        "fragments": [{"start": 318, "end": 521, "type": "CONTINUOUS"}],
                        "hmmBounds": "C_TERMINAL_COMPLETE",
                        "envelopeStart": 315,
                        "envelopeEnd": 521,
                    }
                ],
                "source": "CATH-Gene3D",
            },
            {
                "signature": {
                    "accession": "G3DSA:3.30.200.20",
                    "name": None,
                    "description": "Phosphorylase Kinase; domain 1",
                    "type": "Homologous_superfamily",
                    "signatureLibraryRelease": {
                        "library": "CATH-Gene3D",
                        "version": "4.3.0",
                    },
                    "entry": None,
                },
                "modelAccession": "5vdkA01",
                "score": 110.0,
                "evalue": 1.9e-31,
                "locations": [
                    {
                        "start": 225,
                        "end": 317,
                        "hmmStart": 8,
                        "hmmEnd": 92,
                        "hmmLength": 92,
                        "evalue": 4e-31,
                        "score": 109.0,
                        "fragments": [{"start": 225, "end": 317, "type": "CONTINUOUS"}],
                        "hmmBounds": "N_TERMINAL_COMPLETE",
                        "envelopeStart": 225,
                        "envelopeEnd": 319,
                    }
                ],
                "source": "CATH-Gene3D",
            },
            {
                "signature": {
                    "accession": "Coil",
                    "name": None,
                    "description": "Coil",
                    "type": "Region",
                    "signatureLibraryRelease": {"library": "COILS", "version": "2.2.1"},
                    "entry": None,
                },
                "modelAccession": "Coil",
                "locations": [
                    {
                        "start": 532,
                        "end": 566,
                        "fragments": [{"start": 532, "end": 566, "type": "CONTINUOUS"}],
                    }
                ],
                "source": "COILS",
            },
            {
                "signature": {
                    "accession": "G3DSA:3.30.200.20:FF:000115",
                    "name": None,
                    "description": "Wee1-like kinase 2",
                    "type": "Region",
                    "signatureLibraryRelease": {
                        "library": "CATH-FunFam",
                        "version": "4.3.0",
                    },
                    "entry": None,
                },
                "modelAccession": "3.30.200.20-FF-000115",
                "score": 161.9,
                "evalue": 1.1e-47,
                "locations": [
                    {
                        "start": 228,
                        "end": 317,
                        "hmmStart": 2,
                        "hmmEnd": 90,
                        "hmmLength": 90,
                        "evalue": 2e-47,
                        "score": 161.0,
                        "fragments": [{"start": 228, "end": 317, "type": "CONTINUOUS"}],
                        "hmmBounds": "C_TERMINAL_COMPLETE",
                        "envelopeStart": 228,
                        "envelopeEnd": 317,
                    }
                ],
                "source": "CATH-FunFam",
            },
            {
                "signature": {
                    "accession": "cd14051",
                    "name": "PTKc_Wee1",
                    "description": "Catalytic domain of the Protein Tyrosine Kinase, Wee1",
                    "type": "Domain",
                    "signatureLibraryRelease": {"library": "CDD", "version": "3.21"},
                    "entry": None,
                },
                "modelAccession": "cd14051",
                "locations": [
                    {
                        "start": 238,
                        "end": 516,
                        "evalue": 0.0,
                        "score": 536.217,
                        "fragments": [{"start": 238, "end": 516, "type": "CONTINUOUS"}],
                        "sites": [
                            {
                                "description": "polypeptide substrate binding site",
                                "numLocations": 11,
                                "siteLocations": [
                                    {"start": 323, "end": 323, "residue": "S"},
                                    {"start": 249, "end": 249, "residue": "E"},
                                    {"start": 428, "end": 428, "residue": "D"},
                                    {"start": 430, "end": 430, "residue": "R"},
                                    {"start": 361, "end": 361, "residue": "D"},
                                    {"start": 415, "end": 415, "residue": "H"},
                                    {"start": 365, "end": 365, "residue": "E"},
                                    {"start": 325, "end": 325, "residue": "H"},
                                    {"start": 363, "end": 363, "residue": "K"},
                                    {"start": 427, "end": 427, "residue": "G"},
                                    {"start": 429, "end": 429, "residue": "C"},
                                ],
                                "source": "CDD-3.21",
                            },
                            {
                                "description": "activation loop (A-loop)",
                                "numLocations": 20,
                                "siteLocations": [
                                    {"start": 417, "end": 417, "residue": "T"},
                                    {"start": 415, "end": 415, "residue": "H"},
                                    {"start": 422, "end": 422, "residue": "P"},
                                    {"start": 421, "end": 421, "residue": "E"},
                                    {"start": 418, "end": 418, "residue": "S"},
                                    {"start": 426, "end": 426, "residue": "E"},
                                    {"start": 416, "end": 416, "residue": "V"},
                                    {"start": 411, "end": 411, "residue": "G"},
                                    {"start": 427, "end": 427, "residue": "G"},
                                    {"start": 425, "end": 425, "residue": "E"},
                                    {"start": 423, "end": 423, "residue": "Y"},
                                    {"start": 412, "end": 412, "residue": "D"},
                                    {"start": 428, "end": 428, "residue": "D"},
                                    {"start": 413, "end": 413, "residue": "L"},
                                    {"start": 430, "end": 430, "residue": "R"},
                                    {"start": 414, "end": 414, "residue": "G"},
                                    {"start": 424, "end": 424, "residue": "V"},
                                    {"start": 420, "end": 420, "residue": "K"},
                                    {"start": 419, "end": 419, "residue": "V"},
                                    {"start": 429, "end": 429, "residue": "C"},
                                ],
                                "source": "CDD-3.21",
                            },
                            {
                                "description": "ATP binding site",
                                "numLocations": 20,
                                "siteLocations": [
                                    {"start": 323, "end": 323, "residue": "S"},
                                    {"start": 318, "end": 318, "residue": "F"},
                                    {"start": 300, "end": 300, "residue": "V"},
                                    {"start": 361, "end": 361, "residue": "D"},
                                    {"start": 247, "end": 247, "residue": "V"},
                                    {"start": 366, "end": 366, "residue": "N"},
                                    {"start": 319, "end": 319, "residue": "C"},
                                    {"start": 266, "end": 266, "residue": "A"},
                                    {"start": 363, "end": 363, "residue": "K"},
                                    {"start": 246, "end": 246, "residue": "G"},
                                    {"start": 268, "end": 268, "residue": "K"},
                                    {"start": 249, "end": 249, "residue": "E"},
                                    {"start": 412, "end": 412, "residue": "D"},
                                    {"start": 245, "end": 245, "residue": "I"},
                                    {"start": 248, "end": 248, "residue": "G"},
                                    {"start": 317, "end": 317, "residue": "E"},
                                    {"start": 365, "end": 365, "residue": "E"},
                                    {"start": 253, "end": 253, "residue": "V"},
                                    {"start": 316, "end": 316, "residue": "N"},
                                    {"start": 368, "end": 368, "residue": "F"},
                                ],
                                "source": "CDD-3.21",
                            },
                            {
                                "description": "active site",
                                "numLocations": 26,
                                "siteLocations": [
                                    {"start": 318, "end": 318, "residue": "F"},
                                    {"start": 300, "end": 300, "residue": "V"},
                                    {"start": 247, "end": 247, "residue": "V"},
                                    {"start": 266, "end": 266, "residue": "A"},
                                    {"start": 249, "end": 249, "residue": "E"},
                                    {"start": 412, "end": 412, "residue": "D"},
                                    {"start": 430, "end": 430, "residue": "R"},
                                    {"start": 365, "end": 365, "residue": "E"},
                                    {"start": 325, "end": 325, "residue": "H"},
                                    {"start": 323, "end": 323, "residue": "S"},
                                    {"start": 361, "end": 361, "residue": "D"},
                                    {"start": 415, "end": 415, "residue": "H"},
                                    {"start": 366, "end": 366, "residue": "N"},
                                    {"start": 319, "end": 319, "residue": "C"},
                                    {"start": 363, "end": 363, "residue": "K"},
                                    {"start": 246, "end": 246, "residue": "G"},
                                    {"start": 268, "end": 268, "residue": "K"},
                                    {"start": 427, "end": 427, "residue": "G"},
                                    {"start": 428, "end": 428, "residue": "D"},
                                    {"start": 245, "end": 245, "residue": "I"},
                                    {"start": 248, "end": 248, "residue": "G"},
                                    {"start": 317, "end": 317, "residue": "E"},
                                    {"start": 253, "end": 253, "residue": "V"},
                                    {"start": 316, "end": 316, "residue": "N"},
                                    {"start": 368, "end": 368, "residue": "F"},
                                    {"start": 429, "end": 429, "residue": "C"},
                                ],
                                "source": "CDD-3.21",
                            },
                        ],
                    }
                ],
                "source": "CDD",
            },
            {
                "signature": {
                    "accession": "mobidb-lite",
                    "name": "disorder_prediction",
                    "description": "Consensus disorder prediction",
                    "type": "Region",
                    "signatureLibraryRelease": {
                        "library": "MobiDB-lite",
                        "version": "4.0",
                    },
                    "entry": None,
                },
                "modelAccession": "mobidb-lite",
                "locations": [
                    {
                        "start": 1,
                        "end": 10,
                        "fragments": [{"start": 1, "end": 10, "type": "CONTINUOUS"}],
                        "sequenceFeature": "Polyampholyte",
                    },
                    {
                        "start": 1,
                        "end": 88,
                        "fragments": [{"start": 1, "end": 88, "type": "CONTINUOUS"}],
                        "sequenceFeature": None,
                    },
                    {
                        "start": 37,
                        "end": 48,
                        "fragments": [{"start": 37, "end": 48, "type": "CONTINUOUS"}],
                        "sequenceFeature": "Polyampholyte",
                    },
                    {
                        "start": 147,
                        "end": 166,
                        "fragments": [{"start": 147, "end": 166, "type": "CONTINUOUS"}],
                        "sequenceFeature": None,
                    },
                    {
                        "start": 153,
                        "end": 165,
                        "fragments": [{"start": 153, "end": 165, "type": "CONTINUOUS"}],
                        "sequenceFeature": "Polar",
                    },
                ],
                "source": "MobiDB-lite",
            },
            {
                "signature": {
                    "accession": "PTHR11042",
                    "name": None,
                    "description": "EUKARYOTIC TRANSLATION INITIATION FACTOR 2-ALPHA KINASE EIF2-ALPHA KINASE -RELATED",
                    "type": "Family",
                    "signatureLibraryRelease": {
                        "library": "PANTHER",
                        "version": "19.0",
                    },
                    "entry": {
                        "accession": "IPR050339",
                        "name": "CC_SR_Kinase",
                        "description": "Cell Cycle and Stress Response Kinase",
                        "type": "Family",
                        "parent": None,
                    },
                },
                "modelAccession": "PTHR11042:SF185",
                "ancestralNode": "AN112",
                "evalue": 2.4e-81,
                "score": 285.9,
                "locations": [
                    {
                        "start": 118,
                        "end": 525,
                        "hmmStart": 134,
                        "hmmEnd": 474,
                        "hmmLength": 0,
                        "hmmBounds": "INCOMPLETE",
                        "envelopeStart": 5,
                        "envelopeEnd": 544,
                        "fragments": [{"start": 118, "end": 525, "type": "CONTINUOUS"}],
                    }
                ],
                "source": "PANTHER",
            },
            {
                "signature": {
                    "accession": "PS00107",
                    "name": "PROTEIN_KINASE_ATP",
                    "description": "Protein kinases ATP-binding region signature",
                    "type": "Conserved_site",
                    "signatureLibraryRelease": {
                        "library": "PROSITE patterns",
                        "version": "2025_01",
                    },
                    "entry": {
                        "accession": "IPR017441",
                        "name": "Protein_kinase_ATP_BS",
                        "description": "Protein kinase, ATP binding site",
                        "type": "Binding_site",
                        "parent": None,
                    },
                },
                "modelAccession": "PS00107",
                "locations": [
                    {
                        "start": 245,
                        "end": 269,
                        "cigarAlignment": "10M1I1M9I4M",
                        "fragments": [{"start": 245, "end": 269, "type": "CONTINUOUS"}],
                    }
                ],
                "source": "PROSITE patterns",
            },
            {
                "signature": {
                    "accession": "PS50011",
                    "name": "PROTEIN_KINASE_DOM",
                    "description": "Protein kinase domain profile",
                    "type": "Domain",
                    "signatureLibraryRelease": {
                        "library": "PROSITE profiles",
                        "version": "2025_01",
                    },
                    "entry": {
                        "accession": "IPR000719",
                        "name": "Prot_kinase_dom",
                        "description": "Protein kinase domain",
                        "type": "Domain",
                        "parent": None,
                    },
                },
                "modelAccession": "PS50011",
                "locations": [
                    {
                        "start": 239,
                        "end": 517,
                        "cigarAlignment": "55M1I36M3D1M1I40M33I15M4D17M2D6M2I16M1I1M2D18M1D4M6D32M",
                        "fragments": [{"start": 239, "end": 517, "type": "CONTINUOUS"}],
                        "score": 37.474194,
                    }
                ],
                "source": "PROSITE profiles",
            },
            {
                "signature": {
                    "accession": "PF00069",
                    "name": "Pkinase",
                    "description": "Protein kinase domain",
                    "type": "Domain",
                    "signatureLibraryRelease": {"library": "Pfam", "version": "38.0"},
                    "entry": {
                        "accession": "IPR000719",
                        "name": "Prot_kinase_dom",
                        "description": "Protein kinase domain",
                        "type": "Domain",
                        "parent": None,
                    },
                },
                "modelAccession": "PF00069",
                "score": 161.4,
                "evalue": 9.2e-44,
                "locations": [
                    {
                        "start": 241,
                        "end": 515,
                        "hmmStart": 3,
                        "hmmEnd": 260,
                        "hmmLength": 262,
                        "evalue": 2.9e-43,
                        "score": 159.7,
                        "fragments": [{"start": 241, "end": 515, "type": "CONTINUOUS"}],
                        "hmmBounds": "INCOMPLETE",
                        "envelopeStart": 239,
                        "envelopeEnd": 517,
                    }
                ],
                "source": "Pfam",
            },
            {
                "signature": {
                    "accession": "SM00220",
                    "name": "S_TKc",
                    "description": "Serine/Threonine protein kinases, catalytic domain",
                    "type": "Domain",
                    "signatureLibraryRelease": {"library": "SMART", "version": "9.0"},
                    "entry": {
                        "accession": "IPR000719",
                        "name": "Prot_kinase_dom",
                        "description": "Protein kinase domain",
                        "type": "Domain",
                        "parent": None,
                    },
                },
                "modelAccession": "SM00220",
                "score": 113.3,
                "evalue": 2.7e-29,
                "locations": [
                    {
                        "start": 239,
                        "end": 517,
                        "hmmStart": 1,
                        "hmmEnd": 231,
                        "hmmLength": 231,
                        "evalue": 2.7e-29,
                        "score": 113.3,
                        "fragments": [{"start": 239, "end": 517, "type": "CONTINUOUS"}],
                        "hmmBounds": "COMPLETE",
                    }
                ],
                "source": "SMART",
            },
            {
                "signature": {
                    "accession": "SSF56112",
                    "name": None,
                    "description": "Protein kinase-like (PK-like)",
                    "type": "Homologous_superfamily",
                    "signatureLibraryRelease": {
                        "library": "SUPERFAMILY",
                        "version": "1.75",
                    },
                    "entry": {
                        "accession": "IPR011009",
                        "name": "Kinase-like_dom_sf",
                        "description": "Protein kinase-like domain superfamily",
                        "type": "Homologous_superfamily",
                        "parent": None,
                    },
                },
                "modelAccession": "0040180",
                "evalue": 3.42e-55,
                "locations": [
                    {
                        "start": 228,
                        "end": 527,
                        "hmmLength": 353,
                        "fragments": [
                            {"start": 228, "end": 373, "type": "C_TERMINAL_DISC"},
                            {"start": 405, "end": 527, "type": "N_TERMINAL_DISC"},
                        ],
                    }
                ],
                "source": "SUPERFAMILY",
            },
            {
                "signature": {
                    "accession": "PIRSF037281",
                    "name": "Wee1-like_protein_kinase",
                    "description": "Wee1-like protein kinase",
                    "type": "Family",
                    "signatureLibraryRelease": {"library": "PIRSF", "version": "3.10"},
                    "entry": {
                        "accession": "IPR017164",
                        "name": "Wee1-like_protein_kinase",
                        "description": "Wee1-like protein kinase",
                        "type": "Family",
                        "parent": None,
                    },
                },
                "modelAccession": "PIRSF037281",
                "score": 769.9,
                "evalue": 0.0,
                "locations": [
                    {
                        "start": 2,
                        "end": 592,
                        "hmmStart": 6,
                        "hmmEnd": 585,
                        "hmmLength": 587,
                        "evalue": 0.0,
                        "score": 769.9,
                        "fragments": [{"start": 2, "end": 592, "type": "CONTINUOUS"}],
                        "hmmBounds": "INCOMPLETE",
                        "envelopeStart": 1,
                        "envelopeEnd": 594,
                        "sites": [],
                    }
                ],
                "source": "PIRSF",
            },
        ],
    },
    {
        "md5": "00D88B27726791DDCA7C3CB1601EF2F7",
        "matches": [
            {
                "signature": {
                    "accession": "G3DSA:1.10.510.10",
                    "name": None,
                    "description": "Transferase(Phosphotransferase) domain 1",
                    "type": "Homologous_superfamily",
                    "signatureLibraryRelease": {
                        "library": "CATH-Gene3D",
                        "version": "4.3.0",
                    },
                    "entry": None,
                },
                "modelAccession": "4azsA03",
                "score": 32.3,
                "evalue": 3.8e-07,
                "locations": [
                    {
                        "start": 1,
                        "end": 28,
                        "hmmStart": 19,
                        "hmmEnd": 43,
                        "hmmLength": 162,
                        "evalue": 3.9e-07,
                        "score": 32.3,
                        "fragments": [{"start": 1, "end": 28, "type": "CONTINUOUS"}],
                        "hmmBounds": "COMPLETE",
                        "envelopeStart": 1,
                        "envelopeEnd": 28,
                    }
                ],
                "source": "CATH-Gene3D",
            },
            {
                "signature": {
                    "accession": "PS50011",
                    "name": "PROTEIN_KINASE_DOM",
                    "description": "Protein kinase domain profile",
                    "type": "Domain",
                    "signatureLibraryRelease": {
                        "library": "PROSITE profiles",
                        "version": "2025_01",
                    },
                    "entry": {
                        "accession": "IPR000719",
                        "name": "Prot_kinase_dom",
                        "description": "Protein kinase domain",
                        "type": "Domain",
                        "parent": None,
                    },
                },
                "modelAccession": "PS50011",
                "locations": [
                    {
                        "start": 1,
                        "end": 29,
                        "cigarAlignment": "101D29M129D",
                        "fragments": [{"start": 1, "end": 29, "type": "CONTINUOUS"}],
                        "score": 10.195574,
                    }
                ],
                "source": "PROSITE profiles",
            },
            {
                "signature": {
                    "accession": "SSF56112",
                    "name": None,
                    "description": "Protein kinase-like (PK-like)",
                    "type": "Homologous_superfamily",
                    "signatureLibraryRelease": {
                        "library": "SUPERFAMILY",
                        "version": "1.75",
                    },
                    "entry": {
                        "accession": "IPR011009",
                        "name": "Kinase-like_dom_sf",
                        "description": "Protein kinase-like domain superfamily",
                        "type": "Homologous_superfamily",
                        "parent": None,
                    },
                },
                "modelAccession": "0040179",
                "evalue": 4.91e-08,
                "locations": [
                    {
                        "start": 3,
                        "end": 27,
                        "hmmLength": 350,
                        "fragments": [{"start": 3, "end": 27, "type": "CONTINUOUS"}],
                    }
                ],
                "source": "SUPERFAMILY",
            },
        ],
    },
    {
        "md5": "0038CAF9287BEDBFA5C47D4A2C5FC6F5",
        "matches": [
            {
                "signature": {
                    "accession": "G3DSA:2.40.70.10",
                    "name": None,
                    "description": "Acid Proteases",
                    "type": "Homologous_superfamily",
                    "signatureLibraryRelease": {
                        "library": "CATH-Gene3D",
                        "version": "4.3.0",
                    },
                    "entry": {
                        "accession": "IPR021109",
                        "name": "Peptidase_aspartic_dom_sf",
                        "description": "Aspartic peptidase domain superfamily",
                        "type": "Homologous_superfamily",
                        "parent": None,
                    },
                },
                "modelAccession": "3qvcA02",
                "score": 259.1,
                "evalue": 2.2e-76,
                "locations": [
                    {
                        "start": 65,
                        "end": 222,
                        "hmmStart": 8,
                        "hmmEnd": 238,
                        "hmmLength": 161,
                        "evalue": 3e-76,
                        "score": 258.7,
                        "fragments": [{"start": 65, "end": 222, "type": "CONTINUOUS"}],
                        "hmmBounds": "INCOMPLETE",
                        "envelopeStart": 49,
                        "envelopeEnd": 292,
                    }
                ],
                "source": "CATH-Gene3D",
            },
            {
                "signature": {
                    "accession": "G3DSA:2.40.70.10",
                    "name": None,
                    "description": "Acid Proteases",
                    "type": "Homologous_superfamily",
                    "signatureLibraryRelease": {
                        "library": "CATH-Gene3D",
                        "version": "4.3.0",
                    },
                    "entry": {
                        "accession": "IPR021109",
                        "name": "Peptidase_aspartic_dom_sf",
                        "description": "Aspartic peptidase domain superfamily",
                        "type": "Homologous_superfamily",
                        "parent": None,
                    },
                },
                "modelAccession": "3qvcA01",
                "score": 259.1,
                "evalue": 2.2e-76,
                "locations": [
                    {
                        "start": 55,
                        "end": 286,
                        "hmmStart": 8,
                        "hmmEnd": 238,
                        "hmmLength": 214,
                        "evalue": 3e-76,
                        "score": 258.7,
                        "fragments": [
                            {"start": 55, "end": 64, "type": "C_TERMINAL_DISC"},
                            {"start": 223, "end": 286, "type": "N_TERMINAL_DISC"},
                        ],
                        "hmmBounds": "INCOMPLETE",
                        "envelopeStart": 49,
                        "envelopeEnd": 292,
                    }
                ],
                "source": "CATH-Gene3D",
            },
            {
                "signature": {
                    "accession": "G3DSA:6.10.140.60",
                    "name": None,
                    "description": None,
                    "type": "Homologous_superfamily",
                    "signatureLibraryRelease": {
                        "library": "CATH-Gene3D",
                        "version": "4.3.0",
                    },
                    "entry": None,
                },
                "modelAccession": "1htrP00",
                "score": 46.8,
                "evalue": 8.7e-12,
                "locations": [
                    {
                        "start": 13,
                        "end": 50,
                        "hmmStart": 2,
                        "hmmEnd": 38,
                        "hmmLength": 43,
                        "evalue": 1.4e-11,
                        "score": 46.2,
                        "fragments": [{"start": 13, "end": 50, "type": "CONTINUOUS"}],
                        "hmmBounds": "N_TERMINAL_COMPLETE",
                        "envelopeStart": 13,
                        "envelopeEnd": 52,
                    }
                ],
                "source": "CATH-Gene3D",
            },
            {
                "signature": {
                    "accession": "G3DSA:2.40.70.10:FF:000004",
                    "name": None,
                    "description": "Pepsin A",
                    "type": "Region",
                    "signatureLibraryRelease": {
                        "library": "CATH-FunFam",
                        "version": "4.3.0",
                    },
                    "entry": None,
                },
                "modelAccession": "2.40.70.10-FF-000004",
                "score": 198.0,
                "evalue": 3.6e-58,
                "locations": [
                    {
                        "start": 57,
                        "end": 221,
                        "hmmStart": 7,
                        "hmmEnd": 166,
                        "hmmLength": 167,
                        "evalue": 5e-58,
                        "score": 197.5,
                        "fragments": [{"start": 57, "end": 221, "type": "CONTINUOUS"}],
                        "hmmBounds": "INCOMPLETE",
                        "envelopeStart": 57,
                        "envelopeEnd": 221,
                    }
                ],
                "source": "CATH-FunFam",
            },
            {
                "signature": {
                    "accession": "PTHR47966",
                    "name": None,
                    "description": "BETA-SITE APP-CLEAVING ENZYME, ISOFORM A-RELATED",
                    "type": "Family",
                    "signatureLibraryRelease": {
                        "library": "PANTHER",
                        "version": "19.0",
                    },
                    "entry": {
                        "accession": "IPR001461",
                        "name": "Aspartic_peptidase_A1",
                        "description": "Aspartic peptidase A1",
                        "type": "Family",
                        "parent": None,
                    },
                },
                "modelAccession": "PTHR47966:SF22",
                "ancestralNode": "AN152",
                "evalue": 6.1e-74,
                "score": 261.2,
                "locations": [
                    {
                        "start": 36,
                        "end": 287,
                        "hmmStart": 28,
                        "hmmEnd": 287,
                        "hmmLength": 0,
                        "hmmBounds": "INCOMPLETE",
                        "envelopeStart": 3,
                        "envelopeEnd": 291,
                        "fragments": [{"start": 36, "end": 287, "type": "CONTINUOUS"}],
                    }
                ],
                "source": "PANTHER",
            },
            {
                "signature": {
                    "accession": "PR00792",
                    "name": "PEPSIN",
                    "description": None,
                    "type": "Family",
                    "signatureLibraryRelease": {"library": "PRINTS", "version": "42.0"},
                    "entry": {
                        "accession": "IPR001461",
                        "name": "Aspartic_peptidase_A1",
                        "description": "Aspartic peptidase A1",
                        "type": "Family",
                        "parent": None,
                    },
                },
                "modelAccession": "PR00792",
                "evalue": 9e-17,
                "graphscan": "III.",
                "locations": [
                    {
                        "start": 72,
                        "end": 92,
                        "pvalue": 6.35e-12,
                        "score": 66.52,
                        "motifNumber": 1,
                        "fragments": [{"start": 72, "end": 92, "type": "CONTINUOUS"}],
                    },
                    {
                        "start": 213,
                        "end": 226,
                        "pvalue": 3.53e-05,
                        "score": 32.26,
                        "motifNumber": 2,
                        "fragments": [{"start": 213, "end": 226, "type": "CONTINUOUS"}],
                    },
                    {
                        "start": 262,
                        "end": 273,
                        "pvalue": 2.25e-07,
                        "score": 58.81,
                        "motifNumber": 3,
                        "fragments": [{"start": 262, "end": 273, "type": "CONTINUOUS"}],
                    },
                ],
                "source": "PRINTS",
            },
            {
                "signature": {
                    "accession": "PS00141",
                    "name": "ASP_PROTEASE",
                    "description": "Eukaryotic and viral aspartyl proteases active site",
                    "type": "Conserved_site",
                    "signatureLibraryRelease": {
                        "library": "PROSITE patterns",
                        "version": "2025_01",
                    },
                    "entry": {
                        "accession": "IPR001969",
                        "name": "Aspartic_peptidase_AS",
                        "description": "Aspartic peptidase, active site",
                        "type": "Active_site",
                        "parent": None,
                    },
                },
                "modelAccession": "PS00141",
                "locations": [
                    {
                        "start": 81,
                        "end": 92,
                        "cigarAlignment": "12M",
                        "fragments": [{"start": 81, "end": 92, "type": "CONTINUOUS"}],
                    },
                    {
                        "start": 262,
                        "end": 273,
                        "cigarAlignment": "12M",
                        "fragments": [{"start": 262, "end": 273, "type": "CONTINUOUS"}],
                    },
                ],
                "source": "PROSITE patterns",
            },
            {
                "signature": {
                    "accession": "PS51767",
                    "name": "PEPTIDASE_A1",
                    "description": "Peptidase family A1 domain profile",
                    "type": "Domain",
                    "signatureLibraryRelease": {
                        "library": "PROSITE profiles",
                        "version": "2025_01",
                    },
                    "entry": {
                        "accession": "IPR033121",
                        "name": "PEPTIDASE_A1",
                        "description": "Peptidase family A1 domain",
                        "type": "Domain",
                        "parent": None,
                    },
                },
                "modelAccession": "PS51767",
                "locations": [
                    {
                        "start": 66,
                        "end": 293,
                        "cigarAlignment": "65M1D50M2D26M1D81M1I5M81D",
                        "fragments": [{"start": 66, "end": 293, "type": "CONTINUOUS"}],
                        "score": 52.00724,
                    }
                ],
                "source": "PROSITE profiles",
            },
            {
                "signature": {
                    "accession": "PF00026",
                    "name": "Asp",
                    "description": "Eukaryotic aspartyl protease",
                    "type": "Domain",
                    "signatureLibraryRelease": {"library": "Pfam", "version": "38.0"},
                    "entry": {
                        "accession": "IPR033121",
                        "name": "PEPTIDASE_A1",
                        "description": "Peptidase family A1 domain",
                        "type": "Domain",
                        "parent": None,
                    },
                },
                "modelAccession": "PF00026",
                "score": 252.2,
                "evalue": 2.6e-71,
                "locations": [
                    {
                        "start": 65,
                        "end": 289,
                        "hmmStart": 1,
                        "hmmEnd": 228,
                        "hmmLength": 315,
                        "evalue": 3.1e-71,
                        "score": 252.0,
                        "fragments": [{"start": 65, "end": 289, "type": "CONTINUOUS"}],
                        "hmmBounds": "N_TERMINAL_COMPLETE",
                        "envelopeStart": 65,
                        "envelopeEnd": 293,
                    }
                ],
                "source": "Pfam",
            },
            {
                "signature": {
                    "accession": "PF07966",
                    "name": "A1_Propeptide",
                    "description": "A1 Propeptide",
                    "type": "Conserved_site",
                    "signatureLibraryRelease": {"library": "Pfam", "version": "38.0"},
                    "entry": {
                        "accession": "IPR012848",
                        "name": "Aspartic_peptidase_N",
                        "description": "Aspartic peptidase, N-terminal",
                        "type": "Domain",
                        "parent": None,
                    },
                },
                "modelAccession": "PF07966",
                "score": 34.4,
                "evalue": 4.7e-05,
                "locations": [
                    {
                        "start": 16,
                        "end": 40,
                        "hmmStart": 1,
                        "hmmEnd": 25,
                        "hmmLength": 27,
                        "evalue": 7.5e-05,
                        "score": 33.8,
                        "fragments": [{"start": 16, "end": 40, "type": "CONTINUOUS"}],
                        "hmmBounds": "N_TERMINAL_COMPLETE",
                        "envelopeStart": 16,
                        "envelopeEnd": 42,
                    }
                ],
                "source": "Pfam",
            },
            {
                "signature": {
                    "accession": "SSF50630",
                    "name": None,
                    "description": "Acid proteases",
                    "type": "Homologous_superfamily",
                    "signatureLibraryRelease": {
                        "library": "SUPERFAMILY",
                        "version": "1.75",
                    },
                    "entry": {
                        "accession": "IPR021109",
                        "name": "Peptidase_aspartic_dom_sf",
                        "description": "Aspartic peptidase domain superfamily",
                        "type": "Homologous_superfamily",
                        "parent": None,
                    },
                },
                "modelAccession": "0042297",
                "evalue": 3.97e-82,
                "locations": [
                    {
                        "start": 5,
                        "end": 287,
                        "hmmLength": 375,
                        "fragments": [{"start": 5, "end": 287, "type": "CONTINUOUS"}],
                    }
                ],
                "source": "SUPERFAMILY",
            },
        ],
    },
    {
        "md5": "01B4F93ECDECC0D1FADD32B835DD830C",
        "matches": [
            {
                "signature": {
                    "accession": "NF033819",
                    "name": "IS66_TnpB",
                    "description": "IS66 family insertion sequence element accessory protein TnpB",
                    "type": "Family",
                    "signatureLibraryRelease": {
                        "library": "NCBIFAM",
                        "version": "17.0",
                    },
                    "entry": {
                        "accession": "IPR008878",
                        "name": "Transposase_IS66_Orf2",
                        "description": "Transposase IS66, Orf2",
                        "type": "Family",
                        "parent": None,
                    },
                },
                "modelAccession": "NF033819",
                "score": 125.9,
                "evalue": 1.4e-33,
                "locations": [
                    {
                        "start": 10,
                        "end": 99,
                        "hmmStart": 1,
                        "hmmEnd": 90,
                        "hmmLength": 90,
                        "evalue": 1.7e-33,
                        "score": 125.7,
                        "fragments": [{"start": 10, "end": 99, "type": "CONTINUOUS"}],
                        "hmmBounds": "COMPLETE",
                        "envelopeStart": 10,
                        "envelopeEnd": 99,
                    }
                ],
                "source": "NCBIFAM",
            },
            {
                "signature": {
                    "accession": "PTHR36455",
                    "name": None,
                    "description": None,
                    "type": "Family",
                    "signatureLibraryRelease": {
                        "library": "PANTHER",
                        "version": "19.0",
                    },
                    "entry": {
                        "accession": "IPR008878",
                        "name": "Transposase_IS66_Orf2",
                        "description": "Transposase IS66, Orf2",
                        "type": "Family",
                        "parent": None,
                    },
                },
                "modelAccession": "PTHR36455:SF1",
                "ancestralNode": "AN2",
                "evalue": 3.6e-37,
                "score": 138.0,
                "locations": [
                    {
                        "start": 1,
                        "end": 111,
                        "hmmStart": 1,
                        "hmmEnd": 111,
                        "hmmLength": 0,
                        "hmmBounds": "N_TERMINAL_COMPLETE",
                        "envelopeStart": 1,
                        "envelopeEnd": 114,
                        "fragments": [{"start": 1, "end": 111, "type": "CONTINUOUS"}],
                    }
                ],
                "source": "PANTHER",
            },
            {
                "signature": {
                    "accession": "PF05717",
                    "name": "TnpB_IS66",
                    "description": "IS66 Orf2 like protein",
                    "type": "Family",
                    "signatureLibraryRelease": {"library": "Pfam", "version": "38.0"},
                    "entry": {
                        "accession": "IPR008878",
                        "name": "Transposase_IS66_Orf2",
                        "description": "Transposase IS66, Orf2",
                        "type": "Family",
                        "parent": None,
                    },
                },
                "modelAccession": "PF05717",
                "score": 133.7,
                "evalue": 6e-36,
                "locations": [
                    {
                        "start": 9,
                        "end": 106,
                        "hmmStart": 2,
                        "hmmEnd": 100,
                        "hmmLength": 101,
                        "evalue": 6.8e-36,
                        "score": 133.5,
                        "fragments": [{"start": 9, "end": 106, "type": "CONTINUOUS"}],
                        "hmmBounds": "INCOMPLETE",
                        "envelopeStart": 8,
                        "envelopeEnd": 107,
                    }
                ],
                "source": "Pfam",
            },
        ],
    },
]
single_responses = {
    200: {
        "description": "Success",
        "content": {"application/json": {"example": matches[0]}},
    }
}
batch_responses = {
    200: {
        "description": "Success",
        "content": {
            "application/json": {"example": [{**m, "found": True} for m in matches]}
        },
    }
}
