matches = [
    {
        "md5": "01D251AC732D8184EB086677A9D63ECB",
        "matches": [
            {
                "signature": {
                    "accession": "cd01719",
                    "name": "Sm_G",
                    "description": "Sm protein G",
                    "type": "Domain",
                    "signatureLibraryRelease": {"library": "CDD", "version": "3.21"},
                    "entry": {
                        "accession": "IPR034098",
                        "name": "Sm_G",
                        "description": "Small nuclear ribonucleoprotein G",
                        "type": "Family",
                        "parent": "IPR044641",
                    },
                },
                "modelAccession": "cd01719",
                "source": "CDD",
                "locations": [
                    {
                        "start": 6,
                        "end": 74,
                        "evalue": 4.8074e-40,
                        "score": 124.551,
                        "fragments": [{"start": 6, "end": 74, "type": "CONTINUOUS"}],
                        "sites": [
                            {
                                "description": "Sm2 motif",
                                "numLocations": 12,
                                "siteLocations": [
                                    {"start": 68, "end": 68, "residue": "V"},
                                    {"start": 70, "end": 70, "residue": "V"},
                                    {"start": 59, "end": 59, "residue": "M"},
                                    {"start": 60, "end": 60, "residue": "V"},
                                    {"start": 65, "end": 65, "residue": "N"},
                                    {"start": 64, "end": 64, "residue": "G"},
                                    {"start": 67, "end": 67, "residue": "I"},
                                    {"start": 66, "end": 66, "residue": "S"},
                                    {"start": 61, "end": 61, "residue": "V"},
                                    {"start": 63, "end": 63, "residue": "R"},
                                    {"start": 69, "end": 69, "residue": "T"},
                                    {"start": 62, "end": 62, "residue": "I"},
                                ],
                            },
                            {
                                "description": "heptamer interface",
                                "numLocations": 15,
                                "siteLocations": [
                                    {"start": 70, "end": 70, "residue": "V"},
                                    {"start": 71, "end": 71, "residue": "E"},
                                    {"start": 9, "end": 9, "residue": "D"},
                                    {"start": 64, "end": 64, "residue": "G"},
                                    {"start": 26, "end": 26, "residue": "R"},
                                    {"start": 39, "end": 39, "residue": "M"},
                                    {"start": 69, "end": 69, "residue": "T"},
                                    {"start": 73, "end": 73, "residue": "L"},
                                    {"start": 59, "end": 59, "residue": "M"},
                                    {"start": 68, "end": 68, "residue": "V"},
                                    {"start": 13, "end": 13, "residue": "Y"},
                                    {"start": 21, "end": 21, "residue": "K"},
                                    {"start": 67, "end": 67, "residue": "I"},
                                    {"start": 61, "end": 61, "residue": "V"},
                                    {"start": 62, "end": 62, "residue": "I"},
                                ],
                            },
                            {
                                "description": "Sm1 motif",
                                "numLocations": 25,
                                "siteLocations": [
                                    {"start": 36, "end": 36, "residue": "D"},
                                    {"start": 33, "end": 33, "residue": "R"},
                                    {"start": 42, "end": 42, "residue": "V"},
                                    {"start": 43, "end": 43, "residue": "V"},
                                    {"start": 18, "end": 18, "residue": "L"},
                                    {"start": 24, "end": 24, "residue": "A"},
                                    {"start": 27, "end": 27, "residue": "M"},
                                    {"start": 21, "end": 21, "residue": "K"},
                                    {"start": 23, "end": 23, "residue": "N"},
                                    {"start": 29, "end": 29, "residue": "T"},
                                    {"start": 30, "end": 30, "residue": "G"},
                                    {"start": 37, "end": 37, "residue": "Q"},
                                    {"start": 19, "end": 19, "residue": "Q"},
                                    {"start": 32, "end": 32, "residue": "L"},
                                    {"start": 28, "end": 28, "residue": "V"},
                                    {"start": 34, "end": 34, "residue": "G"},
                                    {"start": 31, "end": 31, "residue": "T"},
                                    {"start": 35, "end": 35, "residue": "F"},
                                    {"start": 26, "end": 26, "residue": "R"},
                                    {"start": 41, "end": 41, "residue": "L"},
                                    {"start": 38, "end": 38, "residue": "F"},
                                    {"start": 20, "end": 20, "residue": "I"},
                                    {"start": 44, "end": 44, "residue": "D"},
                                    {"start": 40, "end": 40, "residue": "N"},
                                    {"start": 22, "end": 22, "residue": "L"},
                                ],
                            },
                            {
                                "description": "RNA binding site",
                                "numLocations": 4,
                                "siteLocations": [
                                    {"start": 38, "end": 38, "residue": "F"},
                                    {"start": 40, "end": 40, "residue": "N"},
                                    {"start": 65, "end": 65, "residue": "N"},
                                    {"start": 63, "end": 63, "residue": "R"},
                                ],
                            },
                        ],
                    }
                ],
            },
            {
                "signature": {
                    "accession": "G3DSA:2.30.30.100",
                    "name": None,
                    "description": None,
                    "type": "Homologous_superfamily",
                    "signatureLibraryRelease": {
                        "library": "CATH-Gene3D",
                        "version": "4.3.0",
                    },
                    "entry": None,
                },
                "modelAccession": "4m75F00",
                "source": "CATH-Gene3D",
                "score": 88.6,
                "evalue": 9.2e-25,
                "locations": [
                    {
                        "start": 1,
                        "end": 76,
                        "hmmStart": 23,
                        "hmmEnd": 106,
                        "hmmLength": 115,
                        "evalue": 1.1e-24,
                        "score": 88.3,
                        "fragments": [{"start": 1, "end": 76, "type": "CONTINUOUS"}],
                        "hmmBounds": "COMPLETE",
                        "envelopeStart": 1,
                        "envelopeEnd": 76,
                    }
                ],
            },
            {
                "signature": {
                    "accession": "G3DSA:2.30.30.100:FF:000023",
                    "name": None,
                    "description": "Small nuclear ribonucleoprotein G",
                    "type": "Region",
                    "signatureLibraryRelease": {
                        "library": "CATH-FunFam",
                        "version": "4.3.0",
                    },
                    "entry": None,
                },
                "modelAccession": "2.30.30.100-FF-000023",
                "source": "CATH-FunFam",
                "score": 147.3,
                "evalue": 3.4e-43,
                "locations": [
                    {
                        "start": 1,
                        "end": 76,
                        "hmmStart": 1,
                        "hmmEnd": 76,
                        "hmmLength": 76,
                        "evalue": 3.7e-43,
                        "score": 147.2,
                        "fragments": [{"start": 1, "end": 76, "type": "CONTINUOUS"}],
                        "hmmBounds": "COMPLETE",
                        "envelopeStart": 1,
                        "envelopeEnd": 76,
                    }
                ],
            },
            {
                "signature": {
                    "accession": "PTHR10553",
                    "name": None,
                    "description": "SMALL NUCLEAR RIBONUCLEOPROTEIN",
                    "type": "Family",
                    "signatureLibraryRelease": {
                        "library": "PANTHER",
                        "version": "19.0",
                    },
                    "entry": {
                        "accession": "IPR044641",
                        "name": "Lsm7/SmG-like",
                        "description": "Sm-like protein Lsm7/SmG",
                        "type": "Family",
                        "parent": None,
                    },
                },
                "modelAccession": "PTHR10553:SF2",
                "source": "PANTHER",
                "annotationNode": "AN257",
                "evalue": 7.9e-33,
                "score": 123.9,
                "locations": [
                    {
                        "start": 3,
                        "end": 77,
                        "hmmStart": 2,
                        "hmmEnd": 75,
                        "hmmLength": 0,
                        "hmmBounds": "INCOMPLETE",
                        "envelopeStart": 1,
                        "envelopeEnd": 80,
                        "fragments": [{"start": 3, "end": 77, "type": "CONTINUOUS"}],
                    }
                ],
            },
            {
                "signature": {
                    "accession": "PIRSF037188",
                    "name": "U6_snRNA_Lsm7",
                    "description": "U6 snRNA-associated Sm-like protein LSm7",
                    "type": "Family",
                    "signatureLibraryRelease": {"library": "PIRSF", "version": "3.10"},
                    "entry": None,
                },
                "modelAccession": "PIRSF037188",
                "source": "PIRSF",
                "score": 68.3,
                "evalue": 9.4e-20,
                "locations": [
                    {
                        "start": 5,
                        "end": 78,
                        "hmmStart": 9,
                        "hmmEnd": 74,
                        "hmmLength": 115,
                        "evalue": 1.5e-19,
                        "score": 67.7,
                        "fragments": [{"start": 5, "end": 78, "type": "CONTINUOUS"}],
                        "hmmBounds": "INCOMPLETE",
                        "envelopeStart": 5,
                        "envelopeEnd": 78,
                    }
                ],
            },
            {
                "signature": {
                    "accession": "PS52002",
                    "name": "SM",
                    "description": "Sm domain profile",
                    "type": "Domain",
                    "signatureLibraryRelease": {
                        "library": "PROSITE profiles",
                        "version": "2023_05",
                    },
                    "entry": {
                        "accession": "IPR047575",
                        "name": "Sm",
                        "description": "Sm domain",
                        "type": "Domain",
                        "parent": None,
                    },
                },
                "modelAccession": "PS52002",
                "source": "PROSITE profiles",
                "locations": [
                    {
                        "start": 5,
                        "end": 76,
                        "cigarAlignment": "46M1D26M",
                        "fragments": [{"start": 5, "end": 76, "type": "CONTINUOUS"}],
                        "score": 29.823053,
                    }
                ],
            },
            {
                "signature": {
                    "accession": "SM00651",
                    "name": "Sm",
                    "description": "snRNP Sm proteins",
                    "type": "Domain",
                    "signatureLibraryRelease": {"library": "SMART", "version": "9.0"},
                    "entry": {
                        "accession": "IPR001163",
                        "name": "Sm_dom_euk/arc",
                        "description": "Sm domain, eukaryotic/archaea-type",
                        "type": "Domain",
                        "parent": "IPR047575",
                    },
                },
                "modelAccession": "SM00651",
                "source": "SMART",
                "score": 93.1,
                "evalue": 3.3e-23,
                "locations": [
                    {
                        "start": 8,
                        "end": 72,
                        "hmmStart": 1,
                        "hmmEnd": 66,
                        "hmmLength": 66,
                        "evalue": 3.3e-23,
                        "score": 93.1,
                        "fragments": [{"start": 8, "end": 72, "type": "CONTINUOUS"}],
                        "hmmBounds": "COMPLETE",
                    }
                ],
            },
            {
                "signature": {
                    "accession": "SSF50182",
                    "name": None,
                    "description": "Sm-like ribonucleoproteins",
                    "type": "Homologous_superfamily",
                    "signatureLibraryRelease": {
                        "library": "SUPERFAMILY",
                        "version": "1.75",
                    },
                    "entry": {
                        "accession": "IPR010920",
                        "name": "LSM_dom_sf",
                        "description": "LSM domain superfamily",
                        "type": "Homologous_superfamily",
                        "parent": None,
                    },
                },
                "modelAccession": "0040799",
                "source": "SUPERFAMILY",
                "evalue": 1.89e-20,
                "locations": [
                    {
                        "start": 9,
                        "end": 75,
                        "hmmLength": 127,
                        "fragments": [{"start": 9, "end": 75, "type": "CONTINUOUS"}],
                    }
                ],
            },
            {
                "signature": {
                    "accession": "PF01423",
                    "name": "LSM",
                    "description": "LSM domain",
                    "type": "Domain",
                    "signatureLibraryRelease": {"library": "Pfam", "version": "37.2"},
                    "entry": {
                        "accession": "IPR001163",
                        "name": "Sm_dom_euk/arc",
                        "description": "Sm domain, eukaryotic/archaea-type",
                        "type": "Domain",
                        "parent": "IPR047575",
                    },
                },
                "modelAccession": "PF01423",
                "source": "Pfam",
                "score": 79.1,
                "evalue": 4.9e-19,
                "locations": [
                    {
                        "start": 9,
                        "end": 71,
                        "hmmStart": 2,
                        "hmmEnd": 65,
                        "hmmLength": 66,
                        "evalue": 5.5e-19,
                        "score": 78.9,
                        "fragments": [{"start": 9, "end": 71, "type": "CONTINUOUS"}],
                        "hmmBounds": "INCOMPLETE",
                        "envelopeStart": 8,
                        "envelopeEnd": 72,
                    }
                ],
            },
        ],
    },
    {
        "md5": "000A144EF6EBDF436875122944286885",
        "matches": [
            {
                "signature": {
                    "accession": "cd00284",
                    "name": "Cytochrome_b_N",
                    "description": None,
                    "type": "Domain",
                    "signatureLibraryRelease": {"library": "CDD", "version": "3.21"},
                    "entry": {
                        "accession": "IPR048259",
                        "name": "Cytochrome_b_N_euk/bac",
                        "description": "Cytochrome b/b6, N-terminal domain, eukaryotic/bacterial",
                        "type": "Domain",
                        "parent": "IPR005797",
                    },
                },
                "modelAccession": "cd00284",
                "source": "CDD",
                "locations": [
                    {
                        "start": 1,
                        "end": 187,
                        "evalue": 9.62525e-95,
                        "score": 275.786,
                        "fragments": [{"start": 1, "end": 187, "type": "CONTINUOUS"}],
                        "sites": [
                            {
                                "description": "intrachain domain interface",
                                "numLocations": 44,
                                "siteLocations": [
                                    {"start": 5, "end": 5, "residue": "P"},
                                    {"start": 116, "end": 116, "residue": "W"},
                                    {"start": 101, "end": 101, "residue": "L"},
                                    {"start": 88, "end": 88, "residue": "Y"},
                                    {"start": 95, "end": 95, "residue": "N"},
                                    {"start": 119, "end": 119, "residue": "M"},
                                    {"start": 72, "end": 72, "residue": "F"},
                                    {"start": 94, "end": 94, "residue": "W"},
                                    {"start": 13, "end": 13, "residue": "N"},
                                    {"start": 12, "end": 12, "residue": "W"},
                                    {"start": 66, "end": 66, "residue": "N"},
                                    {"start": 91, "end": 91, "residue": "M"},
                                    {"start": 44, "end": 44, "residue": "F"},
                                    {"start": 76, "end": 76, "residue": "F"},
                                    {"start": 112, "end": 112, "residue": "Y"},
                                    {"start": 98, "end": 98, "residue": "V"},
                                    {"start": 59, "end": 59, "residue": "L"},
                                    {"start": 135, "end": 135, "residue": "P"},
                                    {"start": 17, "end": 17, "residue": "L"},
                                    {"start": 84, "end": 84, "residue": "Y"},
                                    {"start": 121, "end": 121, "residue": "F"},
                                    {"start": 187, "end": 187, "residue": "N"},
                                    {"start": 83, "end": 83, "residue": "M"},
                                    {"start": 85, "end": 85, "residue": "Y"},
                                    {"start": 122, "end": 122, "residue": "W"},
                                    {"start": 87, "end": 87, "residue": "S"},
                                    {"start": 4, "end": 4, "residue": "A"},
                                    {"start": 70, "end": 70, "residue": "M"},
                                    {"start": 117, "end": 117, "residue": "G"},
                                    {"start": 62, "end": 62, "residue": "Y"},
                                    {"start": 86, "end": 86, "residue": "G"},
                                    {"start": 120, "end": 120, "residue": "S"},
                                    {"start": 126, "end": 126, "residue": "V"},
                                    {"start": 127, "end": 127, "residue": "I"},
                                    {"start": 6, "end": 6, "residue": "S"},
                                    {"start": 102, "end": 102, "residue": "F"},
                                    {"start": 20, "end": 20, "residue": "I"},
                                    {"start": 118, "end": 118, "residue": "Q"},
                                    {"start": 90, "end": 90, "residue": "F"},
                                    {"start": 69, "end": 69, "residue": "S"},
                                    {"start": 63, "end": 63, "residue": "M"},
                                    {"start": 73, "end": 73, "residue": "I"},
                                    {"start": 16, "end": 16, "residue": "S"},
                                    {"start": 67, "end": 67, "residue": "G"},
                                ],
                            },
                            {
                                "description": "heme bH binding site",
                                "numLocations": 22,
                                "siteLocations": [
                                    {"start": 97, "end": 97, "residue": "G"},
                                    {"start": 187, "end": 187, "residue": "N"},
                                    {"start": 101, "end": 101, "residue": "L"},
                                    {"start": 181, "end": 181, "residue": "L"},
                                    {"start": 81, "end": 81, "residue": "R"},
                                    {"start": 78, "end": 78, "residue": "H"},
                                    {"start": 100, "end": 100, "residue": "L"},
                                    {"start": 94, "end": 94, "residue": "W"},
                                    {"start": 18, "end": 18, "residue": "L"},
                                    {"start": 178, "end": 178, "residue": "L"},
                                    {"start": 174, "end": 174, "residue": "V"},
                                    {"start": 12, "end": 12, "residue": "W"},
                                    {"start": 177, "end": 177, "residue": "H"},
                                    {"start": 71, "end": 71, "residue": "F"},
                                    {"start": 15, "end": 15, "residue": "G"},
                                    {"start": 79, "end": 79, "residue": "V"},
                                    {"start": 98, "end": 98, "residue": "V"},
                                    {"start": 75, "end": 75, "residue": "L"},
                                    {"start": 186, "end": 186, "residue": "S"},
                                    {"start": 93, "end": 93, "residue": "T"},
                                    {"start": 16, "end": 16, "residue": "S"},
                                    {"start": 19, "end": 19, "residue": "G"},
                                ],
                            },
                            {
                                "description": "interchain domain interface",
                                "numLocations": 22,
                                "siteLocations": [
                                    {"start": 54, "end": 54, "residue": "V"},
                                    {"start": 34, "end": 34, "residue": "M"},
                                    {"start": 60, "end": 60, "residue": "I"},
                                    {"start": 31, "end": 31, "residue": "F"},
                                    {"start": 183, "end": 183, "residue": "E"},
                                    {"start": 58, "end": 58, "residue": "W"},
                                    {"start": 56, "end": 56, "residue": "Y"},
                                    {"start": 52, "end": 52, "residue": "R"},
                                    {"start": 45, "end": 45, "residue": "S"},
                                    {"start": 35, "end": 35, "residue": "H"},
                                    {"start": 48, "end": 48, "residue": "T"},
                                    {"start": 6, "end": 6, "residue": "S"},
                                    {"start": 49, "end": 49, "residue": "H"},
                                    {"start": 1, "end": 1, "residue": "D"},
                                    {"start": 3, "end": 3, "residue": "P"},
                                    {"start": 44, "end": 44, "residue": "F"},
                                    {"start": 27, "end": 27, "residue": "L"},
                                    {"start": 59, "end": 59, "residue": "L"},
                                    {"start": 55, "end": 55, "residue": "N"},
                                    {"start": 182, "end": 182, "residue": "H"},
                                    {"start": 63, "end": 63, "residue": "M"},
                                    {"start": 53, "end": 53, "residue": "D"},
                                ],
                            },
                            {
                                "description": "Qo binding site",
                                "numLocations": 11,
                                "siteLocations": [
                                    {"start": 126, "end": 126, "residue": "V"},
                                    {"start": 127, "end": 127, "residue": "I"},
                                    {"start": 102, "end": 102, "residue": "F"},
                                    {"start": 159, "end": 159, "residue": "F"},
                                    {"start": 109, "end": 109, "residue": "F"},
                                    {"start": 105, "end": 105, "residue": "M"},
                                    {"start": 131, "end": 131, "residue": "L"},
                                    {"start": 162, "end": 162, "residue": "F"},
                                    {"start": 110, "end": 110, "residue": "M"},
                                    {"start": 106, "end": 106, "residue": "A"},
                                    {"start": 123, "end": 123, "residue": "G"},
                                ],
                            },
                            {
                                "description": "heme bL binding site",
                                "numLocations": 22,
                                "siteLocations": [
                                    {"start": 36, "end": 36, "residue": "Y"},
                                    {"start": 107, "end": 107, "residue": "T"},
                                    {"start": 32, "end": 32, "residue": "L"},
                                    {"start": 25, "end": 25, "residue": "Q"},
                                    {"start": 33, "end": 33, "residue": "A"},
                                    {"start": 65, "end": 65, "residue": "A"},
                                    {"start": 164, "end": 164, "residue": "F"},
                                    {"start": 30, "end": 30, "residue": "L"},
                                    {"start": 68, "end": 68, "residue": "A"},
                                    {"start": 163, "end": 163, "residue": "H"},
                                    {"start": 114, "end": 114, "residue": "L"},
                                    {"start": 115, "end": 115, "residue": "P"},
                                    {"start": 26, "end": 26, "residue": "I"},
                                    {"start": 47, "end": 47, "residue": "V"},
                                    {"start": 111, "end": 111, "residue": "G"},
                                    {"start": 22, "end": 22, "residue": "L"},
                                    {"start": 64, "end": 64, "residue": "H"},
                                    {"start": 112, "end": 112, "residue": "Y"},
                                    {"start": 29, "end": 29, "residue": "G"},
                                    {"start": 108, "end": 108, "residue": "A"},
                                    {"start": 167, "end": 167, "residue": "P"},
                                    {"start": 61, "end": 61, "residue": "R"},
                                ],
                            },
                        ],
                    }
                ],
            },
            {
                "signature": {
                    "accession": "G3DSA:1.20.810.10",
                    "name": None,
                    "description": "Cytochrome Bc1 Complex; Chain C",
                    "type": "Homologous_superfamily",
                    "signatureLibraryRelease": {
                        "library": "CATH-Gene3D",
                        "version": "4.3.0",
                    },
                    "entry": {
                        "accession": "IPR027387",
                        "name": "Cytb/b6-like_sf",
                        "description": "Cytochrome b/b6-like domain superfamily",
                        "type": "Homologous_superfamily",
                        "parent": None,
                    },
                },
                "modelAccession": "3tguC00",
                "source": "CATH-Gene3D",
                "score": 427.6,
                "evalue": 1.2e-127,
                "locations": [
                    {
                        "start": 1,
                        "end": 269,
                        "hmmStart": 21,
                        "hmmEnd": 289,
                        "hmmLength": 380,
                        "evalue": 1.3e-127,
                        "score": 427.4,
                        "fragments": [{"start": 1, "end": 269, "type": "CONTINUOUS"}],
                        "hmmBounds": "COMPLETE",
                        "envelopeStart": 1,
                        "envelopeEnd": 269,
                    }
                ],
            },
            {
                "signature": {
                    "accession": "PTHR19271",
                    "name": None,
                    "description": "CYTOCHROME B",
                    "type": "Family",
                    "signatureLibraryRelease": {
                        "library": "PANTHER",
                        "version": "19.0",
                    },
                    "entry": None,
                },
                "modelAccession": "PTHR19271:SF16",
                "source": "PANTHER",
                "annotationNode": "AN168",
                "evalue": 6.4e-108,
                "score": 372.9,
                "locations": [
                    {
                        "start": 2,
                        "end": 269,
                        "hmmStart": 20,
                        "hmmEnd": 266,
                        "hmmLength": 0,
                        "hmmBounds": "C_TERMINAL_COMPLETE",
                        "envelopeStart": 1,
                        "envelopeEnd": 269,
                        "fragments": [{"start": 2, "end": 269, "type": "CONTINUOUS"}],
                    }
                ],
            },
            {
                "signature": {
                    "accession": "PS51003",
                    "name": "CYTB_CTER",
                    "description": "Cytochrome b/b6 C-terminal region profile",
                    "type": "Domain",
                    "signatureLibraryRelease": {
                        "library": "PROSITE profiles",
                        "version": "2023_05",
                    },
                    "entry": {
                        "accession": "IPR005798",
                        "name": "Cyt_b/b6_C",
                        "description": "Cytochrome b/b6, C-terminal",
                        "type": "Domain",
                        "parent": None,
                    },
                },
                "modelAccession": "PS51003",
                "source": "PROSITE profiles",
                "locations": [
                    {
                        "start": 191,
                        "end": 269,
                        "cigarAlignment": "79M92D",
                        "fragments": [{"start": 191, "end": 269, "type": "CONTINUOUS"}],
                        "score": 28.506851,
                    }
                ],
            },
            {
                "signature": {
                    "accession": "PS51002",
                    "name": "CYTB_NTER",
                    "description": "Cytochrome b/b6 N-terminal region profile",
                    "type": "Domain",
                    "signatureLibraryRelease": {
                        "library": "PROSITE profiles",
                        "version": "2023_05",
                    },
                    "entry": {
                        "accession": "IPR005797",
                        "name": "Cyt_b/b6_N",
                        "description": "Cytochrome b/b6, N-terminal domain",
                        "type": "Domain",
                        "parent": None,
                    },
                },
                "modelAccession": "PS51002",
                "source": "PROSITE profiles",
                "locations": [
                    {
                        "start": 1,
                        "end": 190,
                        "cigarAlignment": "19D88M2D75M1D27M",
                        "fragments": [{"start": 1, "end": 190, "type": "CONTINUOUS"}],
                        "score": 35.983105,
                    }
                ],
            },
            {
                "signature": {
                    "accession": "TRANSMEMBRANE",
                    "name": None,
                    "description": "Transmembrane region",
                    "type": "Region",
                    "signatureLibraryRelease": {
                        "library": "Phobius",
                        "version": "1.01",
                    },
                    "entry": None,
                },
                "modelAccession": "TRANSMEMBRANE",
                "source": "Phobius",
                "locations": [
                    {
                        "start": 12,
                        "end": 36,
                        "fragments": [{"start": 12, "end": 36, "type": "CONTINUOUS"}],
                    },
                    {
                        "start": 56,
                        "end": 77,
                        "fragments": [{"start": 56, "end": 77, "type": "CONTINUOUS"}],
                    },
                    {
                        "start": 89,
                        "end": 114,
                        "fragments": [{"start": 89, "end": 114, "type": "CONTINUOUS"}],
                    },
                    {
                        "start": 120,
                        "end": 147,
                        "fragments": [{"start": 120, "end": 147, "type": "CONTINUOUS"}],
                    },
                    {
                        "start": 159,
                        "end": 180,
                        "fragments": [{"start": 159, "end": 180, "type": "CONTINUOUS"}],
                    },
                    {
                        "start": 210,
                        "end": 231,
                        "fragments": [{"start": 210, "end": 231, "type": "CONTINUOUS"}],
                    },
                ],
            },
            {
                "signature": {
                    "accession": "NON_CYTOPLASMIC_DOMAIN",
                    "name": None,
                    "description": "Non cytoplasmic domain",
                    "type": "Region",
                    "signatureLibraryRelease": {
                        "library": "Phobius",
                        "version": "1.01",
                    },
                    "entry": None,
                },
                "modelAccession": "NON_CYTOPLASMIC_DOMAIN",
                "source": "Phobius",
                "locations": [
                    {
                        "start": 37,
                        "end": 55,
                        "fragments": [{"start": 37, "end": 55, "type": "CONTINUOUS"}],
                    },
                    {
                        "start": 115,
                        "end": 119,
                        "fragments": [{"start": 115, "end": 119, "type": "CONTINUOUS"}],
                    },
                    {
                        "start": 181,
                        "end": 209,
                        "fragments": [{"start": 181, "end": 209, "type": "CONTINUOUS"}],
                    },
                ],
            },
            {
                "signature": {
                    "accession": "CYTOPLASMIC_DOMAIN",
                    "name": None,
                    "description": "Cytoplasmic domain",
                    "type": "Region",
                    "signatureLibraryRelease": {
                        "library": "Phobius",
                        "version": "1.01",
                    },
                    "entry": None,
                },
                "modelAccession": "CYTOPLASMIC_DOMAIN",
                "source": "Phobius",
                "locations": [
                    {
                        "start": 1,
                        "end": 11,
                        "fragments": [{"start": 1, "end": 11, "type": "CONTINUOUS"}],
                    },
                    {
                        "start": 78,
                        "end": 88,
                        "fragments": [{"start": 78, "end": 88, "type": "CONTINUOUS"}],
                    },
                    {
                        "start": 148,
                        "end": 158,
                        "fragments": [{"start": 148, "end": 158, "type": "CONTINUOUS"}],
                    },
                    {
                        "start": 232,
                        "end": 269,
                        "fragments": [{"start": 232, "end": 269, "type": "CONTINUOUS"}],
                    },
                ],
            },
            {
                "signature": {
                    "accession": "SSF81648",
                    "name": None,
                    "description": "a domain/subunit of cytochrome bc1 complex (Ubiquinol-cytochrome c reductase)",
                    "type": "Homologous_superfamily",
                    "signatureLibraryRelease": {
                        "library": "SUPERFAMILY",
                        "version": "1.75",
                    },
                    "entry": {
                        "accession": "IPR036150",
                        "name": "Cyt_b/b6_C_sf",
                        "description": "Cytochrome b/b6, C-terminal domain superfamily",
                        "type": "Homologous_superfamily",
                        "parent": None,
                    },
                },
                "modelAccession": "0037289",
                "source": "SUPERFAMILY",
                "evalue": 2.11e-14,
                "locations": [
                    {
                        "start": 242,
                        "end": 269,
                        "hmmLength": 124,
                        "fragments": [{"start": 242, "end": 269, "type": "CONTINUOUS"}],
                    }
                ],
            },
            {
                "signature": {
                    "accession": "SSF81342",
                    "name": None,
                    "description": "Transmembrane di-heme cytochromes",
                    "type": "Homologous_superfamily",
                    "signatureLibraryRelease": {
                        "library": "SUPERFAMILY",
                        "version": "1.75",
                    },
                    "entry": {
                        "accession": "IPR016174",
                        "name": "Di-haem_cyt_TM",
                        "description": "Di-haem cytochrome, transmembrane",
                        "type": "Homologous_superfamily",
                        "parent": None,
                    },
                },
                "modelAccession": "0035490",
                "source": "SUPERFAMILY",
                "evalue": 6.12e-119,
                "locations": [
                    {
                        "start": 1,
                        "end": 241,
                        "hmmLength": 260,
                        "fragments": [{"start": 1, "end": 241, "type": "CONTINUOUS"}],
                    }
                ],
            },
            {
                "signature": {
                    "accession": "PF00033",
                    "name": "Cytochrome_B",
                    "description": "Cytochrome b/b6/petB",
                    "type": "Domain",
                    "signatureLibraryRelease": {"library": "Pfam", "version": "37.2"},
                    "entry": {
                        "accession": "IPR005797",
                        "name": "Cyt_b/b6_N",
                        "description": "Cytochrome b/b6, N-terminal domain",
                        "type": "Domain",
                        "parent": None,
                    },
                },
                "modelAccession": "PF00033",
                "source": "Pfam",
                "score": 285.8,
                "evalue": 5.1e-82,
                "locations": [
                    {
                        "start": 1,
                        "end": 185,
                        "hmmStart": 3,
                        "hmmEnd": 189,
                        "hmmLength": 189,
                        "evalue": 7e-82,
                        "score": 285.4,
                        "fragments": [{"start": 1, "end": 185, "type": "CONTINUOUS"}],
                        "hmmBounds": "C_TERMINAL_COMPLETE",
                        "envelopeStart": 1,
                        "envelopeEnd": 185,
                    }
                ],
            },
            {
                "signature": {
                    "accession": "PF00032",
                    "name": "Cytochrom_B_C",
                    "description": "Cytochrome b(C-terminal)/b6/petD",
                    "type": "Domain",
                    "signatureLibraryRelease": {"library": "Pfam", "version": "37.2"},
                    "entry": {
                        "accession": "IPR005798",
                        "name": "Cyt_b/b6_C",
                        "description": "Cytochrome b/b6, C-terminal",
                        "type": "Domain",
                        "parent": None,
                    },
                },
                "modelAccession": "PF00032",
                "source": "Pfam",
                "score": 49.3,
                "evalue": 1.5e-09,
                "locations": [
                    {
                        "start": 239,
                        "end": 269,
                        "hmmStart": 1,
                        "hmmEnd": 31,
                        "hmmLength": 102,
                        "evalue": 1.5e-09,
                        "score": 49.3,
                        "fragments": [{"start": 239, "end": 269, "type": "CONTINUOUS"}],
                        "hmmBounds": "N_TERMINAL_COMPLETE",
                        "envelopeStart": 239,
                        "envelopeEnd": 269,
                    }
                ],
            },
        ],
    },
    {
        "md5": "01FAB78080C7D74224138D9BDA9D59CD",
        "matches": [
            {
                "signature": {
                    "accession": "mobidb-lite",
                    "name": "disorder_prediction",
                    "description": "Consensus disorder prediction",
                    "type": "Region",
                    "signatureLibraryRelease": {
                        "library": "MobiDB-lite",
                        "version": "4.0",
                    },
                    "entry": None,
                },
                "modelAccession": "mobidb-lite",
                "source": "MobiDB-lite",
                "locations": [
                    {
                        "start": 93,
                        "end": 107,
                        "fragments": [{"start": 93, "end": 107, "type": "CONTINUOUS"}],
                        "sequenceFeature": "Polar",
                    },
                    {
                        "start": 93,
                        "end": 116,
                        "fragments": [{"start": 93, "end": 116, "type": "CONTINUOUS"}],
                        "sequenceFeature": None,
                    },
                    {
                        "start": 218,
                        "end": 247,
                        "fragments": [{"start": 218, "end": 247, "type": "CONTINUOUS"}],
                        "sequenceFeature": None,
                    },
                    {
                        "start": 228,
                        "end": 246,
                        "fragments": [{"start": 228, "end": 246, "type": "CONTINUOUS"}],
                        "sequenceFeature": "Polar",
                    },
                ],
            },
            {
                "signature": {
                    "accession": "TRANSMEMBRANE",
                    "name": None,
                    "description": "Transmembrane region",
                    "type": "Region",
                    "signatureLibraryRelease": {
                        "library": "Phobius",
                        "version": "1.01",
                    },
                    "entry": None,
                },
                "modelAccession": "TRANSMEMBRANE",
                "source": "Phobius",
                "locations": [
                    {
                        "start": 290,
                        "end": 309,
                        "fragments": [{"start": 290, "end": 309, "type": "CONTINUOUS"}],
                    }
                ],
            },
            {
                "signature": {
                    "accession": "CYTOPLASMIC_DOMAIN",
                    "name": None,
                    "description": "Cytoplasmic domain",
                    "type": "Region",
                    "signatureLibraryRelease": {
                        "library": "Phobius",
                        "version": "1.01",
                    },
                    "entry": None,
                },
                "modelAccession": "CYTOPLASMIC_DOMAIN",
                "source": "Phobius",
                "locations": [
                    {
                        "start": 310,
                        "end": 571,
                        "fragments": [{"start": 310, "end": 571, "type": "CONTINUOUS"}],
                    }
                ],
            },
            {
                "signature": {
                    "accession": "NON_CYTOPLASMIC_DOMAIN",
                    "name": None,
                    "description": "Non cytoplasmic domain",
                    "type": "Region",
                    "signatureLibraryRelease": {
                        "library": "Phobius",
                        "version": "1.01",
                    },
                    "entry": None,
                },
                "source": "Phobius",
                "modelAccession": "NON_CYTOPLASMIC_DOMAIN",
                "locations": [
                    {
                        "start": 1,
                        "end": 289,
                        "fragments": [{"start": 1, "end": 289, "type": "CONTINUOUS"}],
                    }
                ],
            },
        ],
    },
    {
        "md5": "01C79E3EC8E6FC126244DA158CD0DDF0",
        "matches": [
            {
                "signature": {
                    "accession": "G3DSA:2.120.10.30",
                    "name": None,
                    "description": "TolB, C-terminal domain",
                    "type": "Homologous_superfamily",
                    "signatureLibraryRelease": {
                        "library": "CATH-Gene3D",
                        "version": "4.3.0",
                    },
                    "entry": {
                        "accession": "IPR011042",
                        "name": "6-blade_b-propeller_TolB-like",
                        "description": "Six-bladed beta-propeller, TolB-like",
                        "type": "Homologous_superfamily",
                        "parent": None,
                    },
                },
                "source": "CATH-Gene3D",
                "modelAccession": "4gn8A00",
                "score": 307.8,
                "evalue": 2.2e-91,
                "locations": [
                    {
                        "start": 1,
                        "end": 292,
                        "hmmStart": 3,
                        "hmmEnd": 297,
                        "hmmLength": 299,
                        "evalue": 2.6e-91,
                        "score": 307.6,
                        "fragments": [{"start": 1, "end": 292, "type": "CONTINUOUS"}],
                        "hmmBounds": "COMPLETE",
                        "envelopeStart": 1,
                        "envelopeEnd": 292,
                    }
                ],
            },
            {
                "signature": {
                    "accession": "PTHR10907",
                    "name": None,
                    "description": "REGUCALCIN",
                    "type": "Family",
                    "signatureLibraryRelease": {
                        "library": "PANTHER",
                        "version": "19.0",
                    },
                    "entry": None,
                },
                "source": "PANTHER",
                "modelAccession": "PTHR10907:SF47",
                "annotationNode": "AN167",
                "evalue": 3.5e-77,
                "score": 271.1,
                "locations": [
                    {
                        "start": 1,
                        "end": 291,
                        "hmmStart": 17,
                        "hmmEnd": 318,
                        "hmmLength": 0,
                        "hmmBounds": "N_TERMINAL_COMPLETE",
                        "envelopeStart": 1,
                        "envelopeEnd": 293,
                        "fragments": [{"start": 1, "end": 291, "type": "CONTINUOUS"}],
                    }
                ],
            },
            {
                "signature": {
                    "accession": "PR01790",
                    "name": "SMP30FAMILY",
                    "description": None,
                    "type": "Family",
                    "signatureLibraryRelease": {"library": "PRINTS", "version": "42.0"},
                    "entry": {
                        "accession": "IPR005511",
                        "name": "SMP-30",
                        "description": "Senescence marker protein-30 (SMP-30)",
                        "type": "Family",
                        "parent": None,
                    },
                },
                "source": "PRINTS",
                "modelAccession": "PR01790",
                "evalue": 2.6e-33,
                "graphscan": "IIiIII",
                "locations": [
                    {
                        "start": 17,
                        "end": 34,
                        "pvalue": 3.98e-09,
                        "score": 49.18,
                        "motifNumber": 1,
                        "fragments": [{"start": 17, "end": 34, "type": "CONTINUOUS"}],
                    },
                    {
                        "start": 93,
                        "end": 114,
                        "pvalue": 1.17e-08,
                        "score": 43.6,
                        "motifNumber": 2,
                        "fragments": [{"start": 93, "end": 114, "type": "CONTINUOUS"}],
                    },
                    {
                        "start": 137,
                        "end": 159,
                        "pvalue": 0.000465,
                        "score": 26.89,
                        "motifNumber": 3,
                        "fragments": [{"start": 137, "end": 159, "type": "CONTINUOUS"}],
                    },
                    {
                        "start": 160,
                        "end": 180,
                        "pvalue": 5.15e-06,
                        "score": 32.45,
                        "motifNumber": 4,
                        "fragments": [{"start": 160, "end": 180, "type": "CONTINUOUS"}],
                    },
                    {
                        "start": 199,
                        "end": 216,
                        "pvalue": 2.67e-05,
                        "score": 40.53,
                        "motifNumber": 5,
                        "fragments": [{"start": 199, "end": 216, "type": "CONTINUOUS"}],
                    },
                    {
                        "start": 241,
                        "end": 259,
                        "pvalue": 1.27e-09,
                        "score": 49.71,
                        "motifNumber": 6,
                        "fragments": [{"start": 241, "end": 259, "type": "CONTINUOUS"}],
                    },
                ],
            },
            {
                "signature": {
                    "accession": "SSF63829",
                    "name": None,
                    "description": "Calcium-dependent phosphotriesterase",
                    "type": "Homologous_superfamily",
                    "signatureLibraryRelease": {
                        "library": "SUPERFAMILY",
                        "version": "1.75",
                    },
                    "entry": None,
                },
                "source": "SUPERFAMILY",
                "modelAccession": "0052427",
                "evalue": 8.18e-58,
                "locations": [
                    {
                        "start": 9,
                        "end": 291,
                        "hmmLength": 319,
                        "fragments": [{"start": 9, "end": 291, "type": "CONTINUOUS"}],
                    }
                ],
            },
            {
                "signature": {
                    "accession": "PF08450",
                    "name": "SGL",
                    "description": "SMP-30/Gluconolactonase/LRE-like region",
                    "type": "Repeat",
                    "signatureLibraryRelease": {"library": "Pfam", "version": "37.2"},
                    "entry": {
                        "accession": "IPR013658",
                        "name": "SGL",
                        "description": "SMP-30/Gluconolactonase/LRE-like region",
                        "type": "Domain",
                        "parent": None,
                    },
                },
                "source": "Pfam",
                "modelAccession": "PF08450",
                "score": 277.0,
                "evalue": 4.6e-79,
                "locations": [
                    {
                        "start": 16,
                        "end": 259,
                        "hmmStart": 1,
                        "hmmEnd": 245,
                        "hmmLength": 246,
                        "evalue": 5.3e-79,
                        "score": 276.8,
                        "fragments": [{"start": 16, "end": 259, "type": "CONTINUOUS"}],
                        "hmmBounds": "N_TERMINAL_COMPLETE",
                        "envelopeStart": 16,
                        "envelopeEnd": 260,
                    }
                ],
            },
        ],
    },
]
single_responses = {
    200: {
        "description": "Success",
        "content": {"application/json": {"example": matches[0]}},
    }
}
batch_responses = {
    200: {
        "description": "Success",
        "content": {
            "application/json": {"example": [{**m, "found": True} for m in matches]}
        },
    }
}
