FROM python:3.12-alpine

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir .

ENV USER=docker
ENV UID=1257
ENV GID=1134

RUN addgroup --gid "$GID" "$USER" \
  && adduser \
  --disabled-password \
  --gecos "" \
  --home "/app" \
  --ingroup "$USER" \
  --no-create-home \
  --uid "$UID" \
  "$USER"

USER $USER

EXPOSE 8000

CMD ["uvicorn", "matchesapi.main:app", "--host", "0.0.0.0", "--port", "8000", "--root-path", "/interpro/matches/api"]
